# Generated by Django 4.2 on 2023-04-15 15:57

from django.db import migrations, models
import django.db.models.deletion
import tree_menu.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TreeMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TreeMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=255, validators=[tree_menu.models.item_menu_url_validator])),
                ('position', models.IntegerField(blank=True, default=None, null=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_tree_items', to='tree_menu.treemenu')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='tree_menu.treemenuitem')),
            ],
            options={
                'unique_together': {('menu_id', 'url')},
            },
        ),
    ]
