# Generated by Django 4.2 on 2023-04-29 11:29

from django.db import migrations, models
import django.db.models.deletion
import tree_menu.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TreeMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TreeMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=255, validators=[tree_menu.models.item_menu_url_validator])),
                ('left_value', models.IntegerField(default=-1, verbose_name='Order')),
                ('right_value', models.IntegerField(default=-1)),
                ('level', models.IntegerField(default=-1)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_tree_items', to='tree_menu.treemenu')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tree_menu.treemenuitem')),
            ],
            options={
                'ordering': ('menu_id', 'left_value'),
                'unique_together': {('menu_id', 'url')},
            },
        ),
    ]
